### ISSUE TITLE
Support TLS 1.3

### ISSUE THREAD

**Issue by franziskuskiefer** [jmhodges/howsmyssl#118]
It tells me my TLS version is bad because I have TLS 1.3 enabled. I'd suggest to either either ignore higher versions of TLS or explicitly handle 1.3.

**Comment by jmhodges** [comment]
What browser are you using?

The TLS library doesn't support 1.3, so something else might be happening

**Comment by franziskuskiefer** [comment]
I'm using Firefox Nightly with TLS 1.3 enabled (set security.tls.version.max = 4). The same happens with Chrome Canary with 1.3 enabled. So I send a client hello that advertises that I could speak 1.3. As long as the server doesn't support 1.3 it would probably be the easiest to ignore when the client is offering anything higher than 1.2.

**Comment by jmhodges** [comment]
Fixed and deployed!

**Comment by franziskuskiefer** [comment]
👍
