### ISSUE TITLE
connecting to www.howsmyssl.com with SSL3

### ISSUE THREAD

**Issue by Ttxman** [jmhodges/howsmyssl#123]
.NET WebClient with security forced to SSL3 cannot connect to www.howsmyssl.com. 
I think that site that is testing status of client SSL/TLS should support connection via obsolete protocols..

**Comment by jmhodges** [comment]
This seems to be because I accidentally made an ECDSA cert for howsmyssl which isn't supported in SSLv3. Fix coming.

**Comment by jmhodges** [comment]
Okay, fixed. LMK if it still doesn't work for you.
