### ISSUE TITLE
update Google Cloud API client import paths and more

### ISSUE THREAD

**Issue by jba** [jmhodges/howsmyssl#124]
The Google Cloud API client libraries for Go are making some breaking changes:

* The import paths are changing from `google.golang.org/cloud/...` to
  `cloud.google.com/go/...`. For example, if your code imports the BigQuery client
  it currently reads
```import "google.golang.org/cloud/bigquery"```
It should be changed to
```import "cloud.google.com/go/bigquery"```

* Client options are also moving, from `google.golang.org/cloud` to
  `google.golang.org/api/option`. Two have also been renamed:
  - `WithBaseGRPC` is now `WithGRPCConn`
  - `WithBaseHTTP` is now `WithHTTPClient`

* The `cloud.WithContext` and `cloud.NewContext` methods are gone, as are the
deprecated pubsub and container functions that required them. Use the `Client`
methods of these packages instead.

You should make these changes before September 12, 2016, when the packages at
`google.golang.org/cloud` will go away.

**Comment by jmhodges** [comment]
Okay, what's going to happen to the `google.golang.org/api` packages? Similar change?

**Comment by jmhodges** [comment]
I was using the `cloud.WithTokenSource` function as part of a means to load a Google service account file. Is there a replacement API?

I'm sure I just missed something.

The code involved is here (loadGoogleServiceAccount is just a wrapper around a call to `google.JWTConfigFromJSON` that sets the `conf` field mentioned): https://github.com/jmhodges/howsmyssl/blob/093676f7fdd979bb97e8dd1421f019286c09791d/howsmyssl.go#L130-L132

**Comment by jmhodges** [comment]
Oh, I see, that's one of the client options that moved. Thanks!
