### ISSUE TITLE
support TLS 1.3 PSK ciphers

### ISSUE THREAD

**Issue by typingArtist** [jmhodges/howsmyssl#134]
TLS 1.3, now remembered by howsmyssl as A Good Thing to support, specifies some new ciphers that browsers already do support. What’s new about these new ciphers is that they use previous session information, stored at the client side and sent to the server for resuming a previous encrypted session without going through full handshake. This reduces the overhead of session startup considerably and also reduces the time it takes for the session to be up. 

[Appendix A.4, Cipher Suites](https://tlswg.github.io/tls13-spec/#rfc.appendix.A.4) of the latest draft of TLS 1.3 specification, defines five new ciphers of which some are even [declared as mandatory for TLS compliance](https://tlswg.github.io/tls13-spec/#rfc.section.8.1). Note that they only make sense for use if the client already remembers previous session information which can be resumed with. Firefox, for example, gets a ‘probably good’ indication on first connection with https://www.howsmyssl.com, but on a subsequent connection the browser can enable its declaration of PSK cipher suites 0x1301, 0x1303, and 0x1302. howsmyssl marks that as ‘bad’, as unknown ciphers appear.

Please fix the code such that the new ciphers are considered valid and good instead of unknown and bad.

**Comment by jmhodges** [comment]
Took your PR. Thanks!

**Comment by jmhodges** [comment]
It'll be deployed when this Travis CI build goes green: https://travis-ci.org/jmhodges/howsmyssl/builds/165379390

**Comment by jmhodges** [comment]
And done. Have fun!

**Comment by typingArtist** [comment]
works like a charm! Thanks for merging. :smile:
