### ISSUE TITLE
Do something reasonable in the face of GREASE values

### ISSUE THREAD

**Issue by alex** [jmhodges/howsmyssl#138]
https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/a1Sn5b6QuAc

**Comment by alex** [comment]
Current behavior:

![screen shot 2016-10-13 at 12 47 28 pm](https://cloud.githubusercontent.com/assets/772/19358257/3a6d7652-9143-11e6-8c6b-c5e27c11634f.png)

**Comment by jmhodges** [comment]
TLS_GREASE_IS_THE_WORD has been deployed. Enjoy!

Deploy build: https://travis-ci.org/jmhodges/howsmyssl/builds/167418716
