### ISSUE TITLE
Some unknown cipher suite: 0xccaa

### ISSUE THREAD

**Issue by msdsgn** [jmhodges/howsmyssl#143]
`0xCCAA` is apparently `TLS_DHE_RSA_WITH_CHACHA20_POLY1305`, but the server is not recognising the cipher, thus giving an automatic `rating` of `bad` for my client. Queried using the latest OpenSSL 1.1.0b library. The output from your API is below...

`{
   "able_to_detect_n_minus_one_splitting" : 0,
   "beast_vuln" : 0,
   "ephemeral_keys_supported" : 1,
   "given_cipher_suites" : [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
      "Some unknown cipher suite: 0xccaa",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CCM",
      "TLS_DHE_RSA_WITH_AES_256_CCM_8",
      "TLS_DHE_RSA_WITH_AES_256_CCM",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
      "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_WITH_AES_256_CCM_8",
      "TLS_RSA_WITH_AES_256_CCM",
      "TLS_RSA_WITH_AES_256_CBC_SHA256",
      "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_RSA_WITH_AES_256_CBC_SHA",
      "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CCM",
      "TLS_DHE_RSA_WITH_AES_128_CCM_8",
      "TLS_DHE_RSA_WITH_AES_128_CCM",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_128_CCM_8",
      "TLS_RSA_WITH_AES_128_CCM",
      "TLS_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_RSA_WITH_AES_128_CBC_SHA",
      "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
   ],
   "insecure_cipher_suites" : {},
   "rating" : "Bad",
   "session_ticket_supported" : 1,
   "tls_compression_supported" : 0,
   "tls_version" : "TLS 1.2",
   "unknown_cipher_suite_supported" : 1
}`

Good work with the site overall.

**Comment by jmhodges** [comment]
Oh! Thanks for the report. The fix was deployed earlier today.

**Comment by msdsgn** [comment]
Confirmed as fixed, now reporting as `probably okay`. Thank you!
