### ISSUE TITLE
Your SSL is bad ;-)

### ISSUE THREAD

**Issue by joanfabregat** [jmhodges/howsmyssl#145]
Juste a little warning about the SSL configuration of https://www.howsmyssl.com. It seems the configuration still allow the use of SSL3 and therefore is vulnerable to the POODLE attack...

Here are the details:
https://www.ssllabs.com/ssltest/analyze.html?d=www.howsmyssl.com&hideResults=on

**Comment by jmhodges** [comment]
That's required to detect clients that still support SSL3 as their max version. That will go away eventually but not today. There's a other insecurities like that that are required to find the insecurities in the clients.

**Comment by joanfabregat** [comment]
Ok thanks

**Comment by jmhodges** [comment]
Thanks for the report!
