### ISSUE TITLE
'/a/check' JSON always appears to return 'TLS 1.2'

### ISSUE THREAD

**Issue by DanStaal** [jmhodges/howsmyssl#168]
The JSON version of the page always appears to return 'TLS 1.2' - even if the install of curl we're running it with is known to not support TLS 1.2.

**Comment by DanStaal** [comment]
Upon further review, it looks like this is working - something else in our test wasn't.

**Comment by jmhodges** [comment]
Ah, great. Thanks for your patience and update!
