### ISSUE TITLE
Unable to compile howsmyssl.go

### ISSUE THREAD

**Issue by manxjason** [jmhodges/howsmyssl#172]
Latest master commit.

.\howsmyssl.go:267: undefined: originAllower
.\howsmyssl.go:287: undefined: clientInfo
.\howsmyssl.go:296: undefined: clientInfo
.\howsmyssl.go:323: undefined: originAllower

**Comment by jmhodges** [comment]
Can't reproduce over here. Check that your branch is master, it's up to date, and that you didn't accidentally delete some files.

```
git checkout master
git pull origin master
git clean -fdx .
go build .
```

**Comment by jmhodges** [comment]
Feel free to reopen if those things didn't fix your problem.

But if you do, please include how you're building it.

**Comment by manxjason** [comment]
Thanks, new error:

PS C:\Users\jason\Desktop\Src\howsmyssl\howsmyssl> go build .
allow.go:18:2: cannot find package "github.com/dgryski/go-topk" in any of: 
        C:\Go\src\github.com\dgryski\go-topk (from $GOROOT)
