### ISSUE TITLE
Website fails to load in IE with a particular setup

### ISSUE THREAD

**Issue by bpedroza** [jmhodges/howsmyssl#189]
I'm not sure if this is by design or if it's just an oversight, but here is how to recreate the issue:

1. Open IE
2. Go to howsmyssl website
3. Click settings icon -> Internet Options -> Advanced tab
4. Under security: uncheck 'use TLS 1.2' and check 'use SSL 2.0'
5. Reload page

**Comment by jmhodges** [comment]
SSLv2 is not supported by howsmyssl nor every modern browser because it is no longer secure and hasn't been for a couple of decades.

**Comment by jmhodges** [comment]
Thanks for the report!
