### ISSUE TITLE
Add compression to /a/check 

### ISSUE THREAD

**Issue by markpent** [jmhodges/howsmyssl#192]
I use your awesome service on my site to warn customers they will not be able to checkout when they are on an old browser.
Unfortunately, the https://www.howsmyssl.com/a/check url is returning a response that is not compressed, so google page speed check (https://developers.google.com/speed/pagespeed/insights/) complains about it.

If possible, it would be handy if the response was compressed.

Thanks.

**Comment by jmhodges** [comment]
Yeah, sounds good. Since howsmyssl has to hijack the conn, it looks like stuff in its gzip package would have to be exposed to handle it.
