### ISSUE TITLE
Test servers

### ISSUE THREAD

**Issue by kevinburkeotto** [jmhodges/howsmyssl#196]
I would like to test that my (non-public) TLS server is configured securely, presenting a strong ciphersuite, etc.

I would normally use Qualys for this but it's not a public server. This tool seems more aimed at testing clients, unless I'm missing something.

Is there an easy way to use the tools/checks here to test my server's configuration?

**Comment by jmhodges** [comment]
Not easily. There's a few code paths (mostly variable setting) you'd have to copy over to the client side in the fork of `crypto/tls` and then steal conn.go and client_info.go for your own purpose.
