### ISSUE TITLE
https://howsmyssl.com/ has an invalid SSL cert

### ISSUE THREAD

**Issue by MarshallOfSound** [jmhodges/howsmyssl#223]
![screen shot 2018-06-20 at 4 28 06 pm](https://user-images.githubusercontent.com/6634592/41641385-73c3cbdc-74a8-11e8-9868-5b55bc564102.png)

**Comment by jmhodges** [comment]
Yep, fixed. A bad DNS entry. Will take an hour or so to resolve correctly.
