### ISSUE TITLE
Correct 'Version' description in /s/about.html

### ISSUE THREAD

**Issue by alex-d-boyd** [jmhodges/howsmyssl#224]
Currently the 'Version' section reads, "TLS 1.2 is latest version of TLS and it is recommended for clients to implement..."

However, the main page reports, "Your client is using TLS 1.3, the most modern version of the encryption protocol."

Need to update the About page to reflect the availability of TLS 1.3

**Comment by jmhodges** [comment]
Oh this got fixed a long time ago by https://github.com/jmhodges/howsmyssl/pull/246

Have a good one!
