### ISSUE TITLE
https://howsmytls.com/ (Opera : "Your connection is not private")

### ISSUE THREAD

**Issue by aspadistra** [jmhodges/howsmyssl#229]
https://howsmytls.com/ (Opera : "Your connection is not private")

The Full Text

**Your connection is not private**

_This server could not prove that it is howsmytls.com; its security certificate is from subscriptions.howsmyssl.com._ 

_This may be caused by a misconfiguration or an attacker intercepting your connection._

You cannot proceed because the website operator has requested heightened security for this domain.

**Comment by jmhodges** [comment]
Fix. Any particular reason how you came across that domain instead of howsmyssl.com?

**Comment by jmhodges** [comment]
(Thanks, btw!)

**Comment by ASHERH4X** [comment]
Looks like it's happening again!

Found it here:

![image](https://user-images.githubusercontent.com/38171110/56588090-55ce3800-65a8-11e9-86f1-f58080380cb0.png)
