### ISSUE TITLE
TLS Transport, RE "HTML5 Security Tests"

### ISSUE THREAD

**Issue by aspadistra** [jmhodges/howsmyssl#231]
[http://html5test.com/](url) does some Content Security tests, and as far as I can tell these are to do with "End Stage TLS Use" -- if you can get the open source code to test for these it would be nice. End stage use and protection of TLS traffic probably should be part of the equation. 

This should at least be a research consideration. 

Maybe with some crowdfunding these might be added. 

via HTML5 Test Website

Web Cryptography API
No ✘
Content Security Policy 1
Yes ✔
Content Security Policy 2
Yes ✔
Cross-Origin Resource Sharing
Yes ✔
Subresource Integrity
Yes ✔
Cross-document messaging
Yes ✔
Authentication
Web Authentication / FIDO 2
No ✘
Credential Management
No ✘

**Comment by jmhodges** [comment]
Thank you for the ticket! Unfortunately, this is outside the scope of howsmyssl right now
