### ISSUE TITLE
howsmytls.com responds with "404 page not found"

### ISSUE THREAD

**Issue by k2l8m11n2** [jmhodges/howsmyssl#233]
![screenshot](https://user-images.githubusercontent.com/15859761/48676819-1f5d3e80-eb6c-11e8-9519-5f7d677d47bc.png)

**Comment by squid314** [comment]
https://howsmytls.com now responds with a bad cert (cert isn't valid for howsmytls.com). Also since HSTS is enabled, so you can't just continue with the incorrect cert. Looks like howsmytls.com and www.howsmytls.com are just missing from the SANs.

**Comment by jmhodges** [comment]
Busted DNS that's fixed now. However, that's not a supported domain and I'd recommend using howsmyssl.com for the foreseeable future! I was future-proofing in case a rename seemed wise.
