### ISSUE TITLE
Certificate handling

### ISSUE THREAD

**Issue by mnot** [jmhodges/howsmyssl#30]
Test cert validation by the client, to catch the apple dup line bug, as well as other problems. 

This came up in the ietf saag wg meeting in London; apparently NIST has a repository of tests along this line. 

Bonus points for subjectaltname checks and other parts of webpki.

**Comment by jmhodges** [comment]
Applying the multiapi label and closing. If we come up with a new API for handling tests that require multiple connections, it'll go into that. When the multiple connection api is created, we can start looking back into this.
