### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by BobbySig** [jmhodges/howsmyssl#328]
All attempts to reach https://howsmyssl.com/ time out.

**Comment by jberg1** [comment]
2nd that. Looks like it has been down all day.
Site builder - darkishgreen.com is down too.

**Comment by jmhodges** [comment]
Google has apparently lost the entire GKE cluster I was running on today. I'm taking it up with their support.

**Comment by chadpriddle** [comment]
Crashed my Quickbooks API. Looks like its been resolved and site is back up

**Comment by jmhodges** [comment]
Fixed! Sorry for the silence.
