### ISSUE TITLE
howsmyssl fails libsoup-based browser over TLS_DHE_DSS_WITH_RC4_128_SHA support

### ISSUE THREAD

**Issue by Catanzaro** [jmhodges/howsmyssl#35]
libsoup-based web browsers like Epiphany receive a bad rating from howsmyssl.com because:

"Your client supports cipher suites that are known to be insecure:

TLS_DHE_DSS_WITH_RC4_128_SHA: This cipher uses keys smaller than 128 bits in its encryption."

libsoup indirectly uses GnuTLS, and the GnuTLS developers believe this to be a secure cipher suite [1].

It looks like this may already have been fixed by [2], but perhaps not deployed?

[1] https://savannah.gnu.org/support/?108577
[2] https://github.com/jmhodges/howsmyssl/commit/fe3db64430d4792e0d3be0f60a385dbb6cd6cf1b

**Comment by jmhodges** [comment]
Closing this because it was fixed. Also, we're about to remove RC4 completely with #45
