### ISSUE TITLE
OpenSSL name

### ISSUE THREAD

**Issue by 89z** [jmhodges/howsmyssl#353]
current API response is something like this:

~~~
{
   given_cipher_suites: [
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
~~~

It would be helpful in some cases, if the OpenSSL names could be returned instead:

~~~
{
   given_cipher_suites: [
      "ECDHE-ECDSA-AES128-GCM-SHA256",
~~~

<https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256>

**Comment by jmhodges** [comment]
Hm, would need to maintain backwards compatibility. Could you tell me more about your use case?

**Comment by 89z** [comment]
I think I found a workaround - that same site has an API:

https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
