### ISSUE TITLE
Indicate current status for each SSL/TLS protocol

### ISSUE THREAD

**Issue by reedloden** [jmhodges/howsmyssl#39]
I don't know how possible this is considering there's only really one connection from the client to howsmyssl, rather than the other way around (like with SSL Labs's server test), but it would be great if there was a way to figure out the status for each SSL/TLS protocol to see which are enabled (or not).

Perhaps you could use some type of TLS fallback negotiation to help better figure out which SSL/TLS protocol versions are enabled? or could you have it go through a series of redirects that lower the possible SSL/TLS protocol for each new connection? Just brainstorming to see what might be possible.

Probably a lot more is possible if you're using AJAX, but that makes the API side much harder, which is honestly the more useful option.

**Comment by jmhodges** [comment]
Closing as unactionable since this out of line with the current API design.
