### ISSUE TITLE
howsmyssl.com requires vulnerable (old style ssl) negotiation

### ISSUE THREAD

**Issue by ProhtMeyhet** [jmhodges/howsmyssl#42]
1. use firefox
2. in about:config set security.ssl.require_safe_negotiation to true
3. goto https://howsmyssl.com
4. see "Secure Connection Failed
   An error occurred during a connection to www.howsmyssl.com. Peer attempted old style (potentially vulnerable) handshake. (Error code: ssl_error_unsafe_negotiation)"

this should be fixed for a service "that tells you how secure your TLS client is".

see also: https://wiki.mozilla.org/Security:Renegotiation#security.ssl.require_safe_negotiation

**Comment by CHEF-KOCH** [comment]
This is still not fixed, I'm getting the same error with Firefox 38.x and _security.ssl.require_safe_negotiation_ enabled. I'm using TLS 1.2 with AES (256 bit PFS and GCM chipers).

**Comment by jmhodges** [comment]
Firefox 38.0.5 is supposed to be sending 0x00FF TLS_EMPTY_RENEGOTIATION_INFO_SCSV as a cipher suite when requiring safe negotiation per [RFC5746](https://tools.ietf.org/html/rfc5746#page-6) and it does not appear to be doing so.

Instead it sends only these:

	0xC02B: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
	0xC02F: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
	0xC00A: "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
	0xC009: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
	0xC013: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
	0xC014: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
	0x0033: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
	0x0039: "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
	0x002F: "TLS_RSA_WITH_AES_128_CBC_SHA",
	0x0035: "TLS_RSA_WITH_AES_256_CBC_SHA",
	0x000A: "TLS_RSA_WITH_3DES_EDE_CBC_SHA",

This is on TLS 1.2. This is not a howsmyssl bug, but a Firefox bug. Talk to them about it.
