### ISSUE TITLE
How is Session Ticket Support boolean passed?

### ISSUE THREAD

**Issue by igalci** [jmhodges/howsmyssl#434]
This may not be the right place to post it. But I have 2 scripts that I am trying to debug in Python.

One uses urllib3 and the other uses urllib. Both are using the same `ssl` library and both use TLS 1.3.

However, one request shows the `session_ticket_supported` is true, while the other is false.

Any idea of why that is? how is this support boolean created?

**Comment by jmhodges** [comment]
Sorry, this ticket slipped by me. I suspect that this is one of those libraries supporting session tickets and the other does not. It's fairly well-known that `urllib3` does more modern things. You'd have to talk to the folks in the Python community to learn more.
