### ISSUE TITLE
howsmyssl.com domain certificate and configuration issues

### ISSUE THREAD

**Issue by tombrossman** [jmhodges/howsmyssl#44]
I just tested the howsmyssl.com domain with Qualys' SSL Labs tester and it raised multiple issues. Full results are here: https://www.ssllabs.com/ssltest/analyze.html?d=howsmyssl.com

The howsmyssl.com site itself is great and very helpful - thanks for making it available - but I wonder if these points should be addressed?

1. Site uses a weak SHA-1 intermediate certificate
2. Server supports insecure SSLv3 protocol
3. No Forward Secrecy support
4. Weak RC4 Cipersuite supported

These may not be important enough to fix right away but following Mozilla's [Server Side TLS documentation](https://wiki.mozilla.org/Security/Server_Side_TLS) could get you an easy 'A' grade and boost the security of your website.

**Comment by jmhodges** [comment]
All of these things are necessary in order to test older clients. Howsmyssl is a testing tool, not just a website.
