### ISSUE TITLE
Probably okay?

### ISSUE THREAD

**Issue by hickford** [jmhodges/howsmyssl#48]
> Your SSL client is Probably Okay.

I think it's more likely our TLS clients (and the protocol itself) are all insecure, vulnerable to attacks that haven't been published yet. Who knows what catchy named attacks 2016 will bring, but we'll probably need patches.

A more accurate message might be:

> Your SSL client is okay—so far as we know

Just a musing. I don't expect any change. Great project.

**Comment by jmhodges** [comment]
Yeah, no. The language was chosen intentionally and "probably" is fine.
