### ISSUE TITLE
Make Secure - Use Different Subdomains For Testing

### ISSUE THREAD

**Issue by war59312** [jmhodges/howsmyssl#49]
Hi,

Please make the testing site secure.

See security report @ https://www.ssllabs.com/ssltest/analyze.html?d=howsmyssl.com

You should run the tests on other subdomains, just in case they get hacked.

Like how https://rc4.io/ does it. The tests on run on different subdomains.

Thanks,

Will

**Comment by jmhodges** [comment]
Thanks but no. There is no win gained by putting it on another subdomain, the same data can be spoofed either way.

Also, it currently doesn't need any JavaScript to work correctly as using a subdomain would. Without a larger win (like testing things that need connection failures for "success"), doing that isn't a big enough win.

**Comment by war59312** [comment]
Got ya. No worries. Thanks for answering my concern.
