### ISSUE TITLE
Is it access by jsonp?

### ISSUE THREAD

**Issue by yyq2013** [jmhodges/howsmyssl#50]
Hi,
This rest url is very useful for us, because of CORS, we can't access it by ajax in our pages, so do you consider publish a jsonp url?

https://www.howsmyssl.com/a/check

**Comment by jmhodges** [comment]
No, there will be no JSONP API. It's too fragile and finicky to get right.

I would be willing to look at a patch to add the right Access-Control-Allow-Origin and
Access-Control-Allow-Methods headers to correct CORS support.
