### ISSUE TITLE
Support AES-CCM Elliptic Curve Cryptography (ECC) -- RFC 7251

### ISSUE THREAD

**Issue by Swyter** [jmhodges/howsmyssl#51]
What about supporting the following ciphersuites?

```
CipherSuite TLS_ECDHE_ECDSA_WITH_AES_128_CCM = {0xC0,0xAC}
CipherSuite TLS_ECDHE_ECDSA_WITH_AES_256_CCM = {0xC0,0xAD}
CipherSuite TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 = {0xC0,0xAE}
CipherSuite TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8 = {0xC0,0xAF}
```

As defined by this https://tools.ietf.org/html/rfc7251

> This memo describes the use of the Advanced Encryption Standard (AES)
in the Counter and CBC-MAC Mode (CCM) of operation within Transport
Layer Security (TLS) to provide confidentiality and data-origin
authentication.  The AES-CCM algorithm is amenable to compact
implementations, making it suitable for constrained environments,
while at the same time providing a high level of security.  The
cipher suites defined in this document use Elliptic Curve
Cryptography (ECC) and are advantageous in networks with limited
bandwidth.

I have a mbedTLS-based client (the _ReactOS_ secure sockets support layer) which shows up as bad because you guys haven't filled the look-up arrays with these high-security ciphers for embedded clients.

**Comment by Swyter** [comment]
@jmhodges: Any feedback?

**Comment by jmhodges** [comment]
Sorry, my work on Let's Encrypt has kept me too busy to investigate. I'll try to, soon.

**Comment by Swyter** [comment]
Now that _Let's Encrypt_ is in public beta it would be great if you could take a look.
Nice work with the ACME protocol and all that, by the way. This is a game changer!

**Comment by Swyter** [comment]
Merging pull request #54 should fix it. You haven't updated the ciphersuite list from IANA since 2014!
