### ISSUE TITLE
EXP1024-RC4-MD5 and EXP1024-RC2-CBC-MD5 not recognized

### ISSUE THREAD

**Issue by lainegholson** [jmhodges/howsmyssl#56]
`EXP1024-RC4-MD5` and `EXP1024-RC2-CBC-MD5` are shown as unknown ciphers (`0x0060` and `0x0061`, respectively). They are *very* weak, and should be marked as weak because they use 56-bit encryption.

**Comment by jmhodges** [comment]
Please send a PR with links to docs for those cipher suites.
