### ISSUE TITLE
SSL of the server

### ISSUE THREAD

**Issue by IDKwhattoputhere** [jmhodges/howsmyssl#58]
Please take a look here: https://www.ssllabs.com/ssltest/analyze.html?d=howsmyssl.com

Is it right for howsmyssl.com to only get a C? Does the site have to accept SSL3 and be vulnurable to test the visitor for it? And what about adding TLS_FALLBACK_SCSV to prevent protocol downgrade attacks? Sorry if this is a dumb question.

**Comment by jmhodges** [comment]
Yes, that's fine. It's because howsmyssl has to actually test for old, busted clients.
