### ISSUE TITLE
Forcing 301 http response code

### ISSUE THREAD

**Issue by Owen37A** [jmhodges/howsmyssl#61]
Somewhere, somehow, when howsmyssl is running on our server (and we call it with javascript), our site URL is getting hijacked because a 301 response code is happening. We're using IIS for our main site (and the 301 is not in the IIS log-file, so I'm assuming it's coming from howsmyssl).

I found a redirect in howsmyssl.go that looks like this:
```
func commonRedirect(redirectHost string) http.Handler {
	hf := func(w http.ResponseWriter, r *http.Request) {
		commonRedirects.Add(1)
		if r.Header.Get(xForwardedProto) == "https" {
			w.Header().Set("Strict-Transport-Security", hstsHeaderValue)
		}
		u := r.URL
		// Never set by the Go HTTP library.
		u.Scheme = "https"
		u.Host = redirectHost
		http.Redirect(w, r, u.String(), http.StatusMovedPermanently)
	}
	return http.HandlerFunc(hf)
}
```

However, after chaning the StatusMovedPermanently to StatusFound, nothing changed: I'm still getting a 301 from somewhere.

Thoughts?
--Owen

**Comment by jmhodges** [comment]
Not sure! Sounds like it'd be in your IIS config.

You could test it by running your prod config for howsmyssl locally with hacks to whatever the equivalent to /etc/hosts is on Windows.

I'm going to close this since it doesn't seem like a howsmyssl bug.

**Comment by Owen37A** [comment]
CRAP! This went to my spam folder and I just now saw it... You're probably
right that it's something to do with IIS config (or a bug there). I scoured
the howsmyssl code for something that may have set response code 301 (found
one instance and set it to explicitly 302 with no change).  So, unless the
GO library has a bug....

Thanks,
Owen
