### ISSUE TITLE
Not working in IE 8

### ISSUE THREAD

**Issue by keith5000** [jmhodges/howsmyssl#68]
Calling https://www.howsmyssl.com/a/check from an IE8 browser is failing because of an SSL certificate error, which unfortunately makes this tool ineffective for IE8. (Sorry if this is not the right forum to report this since it's not a code bug.)

If I visit https://www.howsmyssl.com in IE8 I get this warning:
![screen2](https://cloud.githubusercontent.com/assets/5175635/14389723/f67efe52-fd81-11e5-839d-4cd46d69e17a.PNG)

When I continue past the warning and look at the certificate error, I see that IE8 thinks the cert is for a different site.
![screen3](https://cloud.githubusercontent.com/assets/5175635/14389741/03528c2a-fd82-11e5-94b8-7b78e6dff4a3.PNG)

The cert looks fine to me and does not generate an error in IE 11 or other modern browsers. Possibly a problem with IE8 not recognizing modern certs?

**Comment by jmhodges** [comment]
Yeah, this sounds like a problem related to the fact that IE 8 doesn't support SNI but the domain you have in the UI is actually the common name. But perhaps you went to howsmyssl.com first and the UI is lying to us about which it was checking against? It might also be that the root the Let's Encrypt cert is signed against doesn't exist on your OS that IE 8 is installed on.

Without having whatever windows OS you're on to debug, I can't really help you much. You'll have to dig in yourself.

**Comment by jmhodges** [comment]
Ahhh, apparently, I thought I had renewed my cert after Let's Encrypt had started being able to support Windows XP again, but, instead, did it right before. There's a "no .mil sites" constraint in the LE intermediate that XP hates and that LE had removed. Will fix.

**Comment by keith5000** [comment]
Awesome, thanks for checking! In case it helps and since you asked, I went to www.howsmyssl.com, not howsmyssl.com.

**Comment by jmhodges** [comment]
This should be fixed now.

**Comment by keith5000** [comment]
Looks good on my end now. Thank you!

**Comment by jmhodges** [comment]
Great!
