### ISSUE TITLE
500 Errors

### ISSUE THREAD

**Issue by DirtC** [jmhodges/howsmyssl#70]
Hi guys,

First, thanks for this project. It has been great!

We've been getting a lot of site slowdowns because we're using the functions to test for TLS settings. The anecdotal evidence is that the page takes forever to render because we're waiting on the TLS check to complete (we have to show a warning if the browser doesn't pass muster). 

Using fiddler I have occasionally seen 502 errors. 

Can you let me know if you're under heavy load or something is amiss? 

Thanks!

**Comment by jmhodges** [comment]
There has been an uptick in traffic. Who's "we" in your context? 

I'd strongly recommend using your own installation of howsmyssl. As a free, public service, howsmyssl's latency and uptime are not guaranteed.

**Comment by DirtC** [comment]
That's what I was figuring, but wanted to reach out and make sure you knew about it, regardless. Ok, thanks. Great tool!
